import { StyleSheet } from 'react-native';
import colors from '../colors';
import { radius, spacing, font, shadow } from '../tokens';

const styles = StyleSheet.create({
  container: { padding: spacing.md, backgroundColor: colors.background, flexGrow: 1, paddingBottom: spacing.xxl - 4, gap: spacing.sm },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background, padding: spacing.lg, gap: spacing.md },
  loadingText: { marginTop: 10, color: colors.textGray, fontWeight: font.weight.semibold, textAlign: 'center' },
  hero: { backgroundColor: colors.navy, borderRadius: radius.lg, padding: spacing.lg - 1, borderLeftWidth: 4, borderLeftColor: colors.electricBlue, ...shadow.md },
  heroTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.md - 2 },
  heroBadge: { backgroundColor: 'rgba(255,255,255,0.12)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.18)', borderRadius: radius.pill, paddingHorizontal: 10, paddingVertical: 6 },
  heroBadgeText: { color: colors.white, fontWeight: font.weight.bold, fontSize: 12 },
  heroTitle: { color: colors.white, fontWeight: font.weight.black, fontSize: font.size.display, marginBottom: 6 },
  heroSubtitle: { color: '#DCEBFF', lineHeight: 20, fontWeight: font.weight.regular },
  heroHighlight: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.lg - 2, backgroundColor: 'rgba(255,255,255,0.10)', borderRadius: radius.md, borderWidth: 1, borderColor: 'rgba(255,255,255,0.14)', padding: spacing.sm + 1 },
  heroHighlightItem: { flex: 1 },
  heroHighlightValue: { color: colors.white, fontSize: font.size.display, fontWeight: font.weight.black },
  heroHighlightLabel: { color: '#BFDBFE', fontWeight: font.weight.bold, marginTop: 2 },
  heroDivider: { width: 1, height: 46, backgroundColor: 'rgba(255,255,255,0.25)', marginHorizontal: 10 },
  heroAlert: { marginTop: spacing.sm, backgroundColor: 'rgba(239,68,68,0.16)', borderRadius: radius.sm, padding: 10, borderLeftWidth: 3, borderLeftColor: colors.riskRed },
  heroAlertText: { color: colors.white, fontWeight: font.weight.bold, lineHeight: 18 },
  heroActions: { flexDirection: 'row', gap: 8, marginTop: spacing.md - 2 },
  actionButton: { flex: 1, backgroundColor: colors.fordBlue, borderRadius: radius.md, paddingVertical: 12, alignItems: 'center', justifyContent: 'center', ...shadow.glowBlue },
  actionButtonSecondary: { backgroundColor: colors.white, shadowOpacity: 0, elevation: 0 },
  actionButtonText: { color: colors.white, fontWeight: font.weight.bold, fontSize: 13 },
  actionButtonTextSecondary: { color: colors.navy },
  metricsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 10 },
  metricCard: { width: '48%', borderWidth: 1, borderRadius: radius.lg, padding: spacing.md - 2, backgroundColor: colors.surface, ...shadow.sm },
  metricTitle: { color: colors.textGray, fontWeight: font.weight.bold, fontSize: 12 },
  metricValue: { color: colors.navy, fontWeight: font.weight.black, fontSize: font.size.display, marginVertical: 6 },
  metricSubtitle: { color: colors.muted, fontSize: 12, fontWeight: font.weight.regular },
  metric_blue: { borderColor: '#CFE0FF', backgroundColor: colors.surface },
  metric_red: { borderColor: '#FFC9CE', backgroundColor: colors.riskRedSoft },
  metric_yellow: { borderColor: '#FDE1A8', backgroundColor: colors.warningSoft },
  metric_purple: { borderColor: '#E9D5FF', backgroundColor: colors.purpleSoft },
  sectionCard: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, padding: spacing.md, ...shadow.sm },
  sectionTitle: { fontWeight: font.weight.black, color: colors.navy, fontSize: font.size.xl, marginBottom: 4 },
  sectionSubtitle: { color: colors.textGray, fontWeight: font.weight.regular, lineHeight: 18, marginBottom: spacing.sm },
  tabsRow: { flexDirection: 'row', gap: 8, marginBottom: spacing.sm },
  tabButton: { flex: 1, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceSoft, borderRadius: radius.md, paddingVertical: 10, alignItems: 'center' },
  tabButtonActive: { backgroundColor: colors.fordBlue, borderColor: colors.fordBlue },
  tabButtonText: { color: colors.fordBlue, fontWeight: font.weight.bold, fontSize: 12 },
  tabButtonTextActive: { color: colors.white },
  chartCard: { backgroundColor: colors.surfaceSoft, borderRadius: radius.md, padding: spacing.md - 2, borderWidth: 1, borderColor: colors.borderSoft },
  chartTitle: { fontWeight: font.weight.black, color: colors.navy, fontSize: 15, marginBottom: 4 },
  chartSubtitle: { color: colors.textGray, fontWeight: font.weight.regular, fontSize: 12, lineHeight: 17, marginBottom: spacing.sm - 2 },
  chartList: { gap: 8 },
  chartItem: { paddingVertical: 6, paddingHorizontal: 4, borderRadius: radius.sm },
  chartHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  chartLabel: { color: colors.textDark, fontWeight: font.weight.bold, fontSize: 12, flex: 1, marginRight: 8 },
  chartValue: { color: colors.fordBlue, fontWeight: font.weight.black, fontSize: 12 },
  chartTrack: { height: 8, borderRadius: radius.pill, backgroundColor: '#E8EEF7', overflow: 'hidden' },
  chartFill: { height: 8, borderRadius: radius.pill },
  chartCtaBox: { marginTop: spacing.sm, backgroundColor: colors.white, borderRadius: radius.md, borderWidth: 1, borderColor: colors.borderSoft, padding: spacing.sm },
  chartCtaTitle: { color: colors.navy, fontWeight: font.weight.black, fontSize: 15, marginBottom: 4 },
  chartCtaDescription: { color: '#334155', lineHeight: 19, fontWeight: font.weight.regular, fontSize: 13 },
  chartCtaButton: { marginTop: spacing.sm, backgroundColor: colors.fordBlue, borderRadius: radius.md, paddingVertical: 11, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center', ...shadow.glowBlue },
  chartCtaButtonText: { color: colors.white, fontWeight: font.weight.bold, fontSize: 13 },
});

export default styles;
